adopted: true
description: Executes a SOC Framework action using brand_source mappings and SOCFramework.Artifacts.
dirtyInputs: true
id: soc_generic_action
inputSections:
- description: Generic group for inputs
  inputs:
  - product_category
  - brand_source
  - action
  - artifacts
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: Product Category (Email, Endpoint, Identity, etc.)
  key: product_category
  playbookInputQuery: null
  required: false
  value: {}
- description: Integration sourceBrand pulled from issue/source.
  key: brand_source
  playbookInputQuery: null
  required: false
  value: {}
- description: The SOC action to execute (e.g. soc-quarantine-email)
  key: action
  playbookInputQuery: null
  required: true
  value:
    simple: soc-quarantine-email
- description: ${inputs.Artifacts}
  key: artifacts
  playbookInputQuery: null
  required: false
  value:
    simple: ${inputs.artifacts}
- description: ""
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: SOC Generic Action
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs:
  - SOCFramework.ActionOutput
outputs:
- contextPath: SOCFramework.ActionOutput
  description: Output from the executed command.
starttaskid: "0"
tags:
- SOC
- SOC_Framework
- Commands
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e4ac8529-7832-4305-8ad6-e2ed83c2dfc7
      iscommand: false
      name: Start
      playbooktaskmissingcomponent: null
      version: -1
    taskid: e4ac8529-7832-4305-8ad6-e2ed83c2dfc7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 347.5,
          "y": 50
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: errorPath
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "102"
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: ${inputs.action}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3da6734a-1cf2-4fcb-8934-9f389556f272
      iscommand: false
      name: Get Required Artifacts
      playbooktaskmissingcomponent: null
      script: 'SOCFramework-GetRequiredArtifacts'
      type: regular
      version: -1
    taskid: 3da6734a-1cf2-4fcb-8934-9f389556f272
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 347.5,
          "y": 220
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: errorPath
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "102"
      '#none#':
      - "30"
    note: false
    quietmode: 0
    scriptarguments:
      artifacts:
        simple: ${inputs.artifacts}
      required:
        simple: ${SOCFramework.RequiredArtifacts}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09a75bdc-d569-491e-973f-9f1fc38e1236
      iscommand: false
      name: Validate Artifacts
      playbooktaskmissingcomponent: null
      script: 'SOCFramework-ValidateArtifacts'
      type: regular
      version: -1
    taskid: 09a75bdc-d569-491e-973f-9f1fc38e1236
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 400
        }
      }
  "30":
    continueonerror: true
    continueonerrortype: errorPath
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "102"
      '#none#':
      - "103"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: ${inputs.action}
      brand_source:
        simple: ${inputs.brand_source}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 967ea116-74b4-495d-beff-61c094513fc5
      iscommand: false
      name: Get Brand Command
      playbooktaskmissingcomponent: null
      script: 'SOCFramework-GetBrandCommand'
      type: regular
      version: -1
    taskid: 967ea116-74b4-495d-beff-61c094513fc5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 572.5,
          "y": 580
        }
      }
  "40":
    continueonerror: true
    continueonerrortype: errorPath
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "102"
      '#none#':
      - "101"
    note: false
    quietmode: 0
    scriptarguments:
      args_map:
        simple: ${SOCFramework.BrandCommand.args}
      artifacts:
        simple: ${inputs.artifacts}
      command:
        simple: ${SOCFramework.BrandCommand.command}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 453f0dba-c84c-4c12-804a-2b9e121a274a
      iscommand: false
      name: Run Command Wrapper
      playbooktaskmissingcomponent: null
      script: 'SOC_CommandWrapper'
      type: regular
      version: -1
    taskid: 453f0dba-c84c-4c12-804a-2b9e121a274a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 940
        }
      }
  "100":
    continueonerrortype: ""
    id: "100"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 52b33b28-f3e5-4cd7-86bb-6edca553f509
      iscommand: false
      name: Complete
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 52b33b28-f3e5-4cd7-86bb-6edca553f509
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1002.5,
          "y": 1305
        }
      }
  "101":
    continueonerror: true
    continueonerrortype: errorPath
    id: "101"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "102"
      '#none#':
      - "100"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: ${inputs.action}
      brand_source:
        simple: ${inputs.brand_source}
      command:
        simple: ${SOCFramework.BrandCommand.command}
      output:
        simple: ${SOCFramework.ActionOutput}
      product_category:
        simple: ${inputs.product_category}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: abfaac59-b1e5-4ada-8d58-984acdc5f858
      iscommand: false
      name: Write Action History
      playbooktaskmissingcomponent: null
      script: 'SOCFramework-ActionHistoryAdd'
      type: regular
      version: -1
    taskid: abfaac59-b1e5-4ada-8d58-984acdc5f858
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 1120
        }
      }
  "102":
    continueonerrortype: ""
    id: "102"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: aa707eb6-1529-4b87-8021-593b84b9fcdf
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: aa707eb6-1529-4b87-8021-593b84b9fcdf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1300
        }
      }
  "103":
    continueonerrortype: ""
    id: "103"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Full Run:
      - "40"
      Shadow Mode:
      - "104"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${inputs.ShadowMode}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8d21956e-ccc0-4be6-80a9-740cb896c654
      iscommand: false
      name: Full Run or Shadow Mode?
      playbooktaskmissingcomponent: null
      script: ShadowModeRouter
      type: condition
      version: -1
    taskid: 8d21956e-ccc0-4be6-80a9-740cb896c654
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 685,
          "y": 760
        }
      }
  "104":
    continueonerrortype: ""
    id: "104"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "100"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |
          Shadow Mode
          cmd: ${SOCFramework.BrandCommand.command}
          args: ${SOCFramework.BrandCommand.args}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8637006e-419e-442a-a4e0-3fbc550b32de
      iscommand: false
      name: Print Command
      playbooktaskmissingcomponent: null
      script: Print
      type: regular
      version: -1
    taskid: 8637006e-419e-442a-a4e0-3fbc550b32de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1012.5,
          "y": 1120
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1320,
        "width": 1342.5,
        "x": 50,
        "y": 50
      }
    }
  }
